# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1424, 974)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 58, 251, 851))
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(109, 28, 135, 490))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.HPBase = QtWidgets.QLineEdit(self.widget)
        self.HPBase.setReadOnly(True)
        self.HPBase.setObjectName("HPBase")
        self.verticalLayout.addWidget(self.HPBase)
        self.HPScaling = QtWidgets.QLineEdit(self.widget)
        self.HPScaling.setReadOnly(True)
        self.HPScaling.setObjectName("HPScaling")
        self.verticalLayout.addWidget(self.HPScaling)
        self.FeverSpeed = QtWidgets.QLineEdit(self.widget)
        self.FeverSpeed.setReadOnly(True)
        self.FeverSpeed.setObjectName("FeverSpeed")
        self.verticalLayout.addWidget(self.FeverSpeed)
        self.AttackSpeed = QtWidgets.QLineEdit(self.widget)
        self.AttackSpeed.setObjectName("AttackSpeed")
        self.verticalLayout.addWidget(self.AttackSpeed)
        self.SprintSpeed = QtWidgets.QLineEdit(self.widget)
        self.SprintSpeed.setReadOnly(True)
        self.SprintSpeed.setObjectName("SprintSpeed")
        self.verticalLayout.addWidget(self.SprintSpeed)
        self.MinDMG = QtWidgets.QLineEdit(self.widget)
        self.MinDMG.setReadOnly(True)
        self.MinDMG.setObjectName("MinDMG")
        self.verticalLayout.addWidget(self.MinDMG)
        self.MinDMGScaling = QtWidgets.QLineEdit(self.widget)
        self.MinDMGScaling.setReadOnly(True)
        self.MinDMGScaling.setObjectName("MinDMGScaling")
        self.verticalLayout.addWidget(self.MinDMGScaling)
        self.MaxDMG = QtWidgets.QLineEdit(self.widget)
        self.MaxDMG.setReadOnly(True)
        self.MaxDMG.setObjectName("MaxDMG")
        self.verticalLayout.addWidget(self.MaxDMG)
        self.MaxDMGScaling = QtWidgets.QLineEdit(self.widget)
        self.MaxDMGScaling.setReadOnly(True)
        self.MaxDMGScaling.setObjectName("MaxDMGScaling")
        self.verticalLayout.addWidget(self.MaxDMGScaling)
        self.Power = QtWidgets.QLineEdit(self.widget)
        self.Power.setReadOnly(True)
        self.Power.setObjectName("Power")
        self.verticalLayout.addWidget(self.Power)
        self.PowerScaling = QtWidgets.QLineEdit(self.widget)
        self.PowerScaling.setText("")
        self.PowerScaling.setReadOnly(True)
        self.PowerScaling.setObjectName("PowerScaling")
        self.verticalLayout.addWidget(self.PowerScaling)
        self.ShieldBreak = QtWidgets.QLineEdit(self.widget)
        self.ShieldBreak.setReadOnly(True)
        self.ShieldBreak.setObjectName("ShieldBreak")
        self.verticalLayout.addWidget(self.ShieldBreak)
        self.ShieldBreakScaling = QtWidgets.QLineEdit(self.widget)
        self.ShieldBreakScaling.setReadOnly(True)
        self.ShieldBreakScaling.setObjectName("ShieldBreakScaling")
        self.verticalLayout.addWidget(self.ShieldBreakScaling)
        self.Defense = QtWidgets.QLineEdit(self.widget)
        self.Defense.setReadOnly(True)
        self.Defense.setObjectName("Defense")
        self.verticalLayout.addWidget(self.Defense)
        self.DefenseScaling = QtWidgets.QLineEdit(self.widget)
        self.DefenseScaling.setReadOnly(True)
        self.DefenseScaling.setObjectName("DefenseScaling")
        self.verticalLayout.addWidget(self.DefenseScaling)
        self.Evasion = QtWidgets.QLineEdit(self.widget)
        self.Evasion.setReadOnly(True)
        self.Evasion.setObjectName("Evasion")
        self.verticalLayout.addWidget(self.Evasion)
        self.EvasionScaling = QtWidgets.QLineEdit(self.widget)
        self.EvasionScaling.setReadOnly(True)
        self.EvasionScaling.setObjectName("EvasionScaling")
        self.verticalLayout.addWidget(self.EvasionScaling)
        self.Weight = QtWidgets.QLineEdit(self.widget)
        self.Weight.setReadOnly(True)
        self.Weight.setObjectName("Weight")
        self.verticalLayout.addWidget(self.Weight)
        self.WeightScaling = QtWidgets.QLineEdit(self.widget)
        self.WeightScaling.setReadOnly(True)
        self.WeightScaling.setObjectName("WeightScaling")
        self.verticalLayout.addWidget(self.WeightScaling)
        self.widget1 = QtWidgets.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(10, 28, 96, 491))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.HPBase_label = QtWidgets.QLabel(self.widget1)
        self.HPBase_label.setObjectName("HPBase_label")
        self.verticalLayout_5.addWidget(self.HPBase_label)
        self.HPScaling_label = QtWidgets.QLabel(self.widget1)
        self.HPScaling_label.setObjectName("HPScaling_label")
        self.verticalLayout_5.addWidget(self.HPScaling_label)
        self.labelFeverSpeed_label = QtWidgets.QLabel(self.widget1)
        self.labelFeverSpeed_label.setObjectName("labelFeverSpeed_label")
        self.verticalLayout_5.addWidget(self.labelFeverSpeed_label)
        self.AttackSpeed_label = QtWidgets.QLabel(self.widget1)
        self.AttackSpeed_label.setObjectName("AttackSpeed_label")
        self.verticalLayout_5.addWidget(self.AttackSpeed_label)
        self.SprintSpeed_label = QtWidgets.QLabel(self.widget1)
        self.SprintSpeed_label.setObjectName("SprintSpeed_label")
        self.verticalLayout_5.addWidget(self.SprintSpeed_label)
        self.MinDMG_label = QtWidgets.QLabel(self.widget1)
        self.MinDMG_label.setObjectName("MinDMG_label")
        self.verticalLayout_5.addWidget(self.MinDMG_label)
        self.MinDMGScaling_label = QtWidgets.QLabel(self.widget1)
        self.MinDMGScaling_label.setObjectName("MinDMGScaling_label")
        self.verticalLayout_5.addWidget(self.MinDMGScaling_label)
        self.MaxDMG_label = QtWidgets.QLabel(self.widget1)
        self.MaxDMG_label.setObjectName("MaxDMG_label")
        self.verticalLayout_5.addWidget(self.MaxDMG_label)
        self.MaxDMGScaling_label = QtWidgets.QLabel(self.widget1)
        self.MaxDMGScaling_label.setObjectName("MaxDMGScaling_label")
        self.verticalLayout_5.addWidget(self.MaxDMGScaling_label)
        self.Power_label = QtWidgets.QLabel(self.widget1)
        self.Power_label.setObjectName("Power_label")
        self.verticalLayout_5.addWidget(self.Power_label)
        self.PowerScaling_label = QtWidgets.QLabel(self.widget1)
        self.PowerScaling_label.setObjectName("PowerScaling_label")
        self.verticalLayout_5.addWidget(self.PowerScaling_label)
        self.ShieldBreak_label = QtWidgets.QLabel(self.widget1)
        self.ShieldBreak_label.setObjectName("ShieldBreak_label")
        self.verticalLayout_5.addWidget(self.ShieldBreak_label)
        self.ShieldBreakScaling_label = QtWidgets.QLabel(self.widget1)
        self.ShieldBreakScaling_label.setObjectName("ShieldBreakScaling_label")
        self.verticalLayout_5.addWidget(self.ShieldBreakScaling_label)
        self.Defense_label = QtWidgets.QLabel(self.widget1)
        self.Defense_label.setObjectName("Defense_label")
        self.verticalLayout_5.addWidget(self.Defense_label)
        self.DefenseScaling_label = QtWidgets.QLabel(self.widget1)
        self.DefenseScaling_label.setObjectName("DefenseScaling_label")
        self.verticalLayout_5.addWidget(self.DefenseScaling_label)
        self.Evasion_label = QtWidgets.QLabel(self.widget1)
        self.Evasion_label.setObjectName("Evasion_label")
        self.verticalLayout_5.addWidget(self.Evasion_label)
        self.EvasionScaling_label = QtWidgets.QLabel(self.widget1)
        self.EvasionScaling_label.setObjectName("EvasionScaling_label")
        self.verticalLayout_5.addWidget(self.EvasionScaling_label)
        self.Weight_label = QtWidgets.QLabel(self.widget1)
        self.Weight_label.setObjectName("Weight_label")
        self.verticalLayout_5.addWidget(self.Weight_label)
        self.WeightScaling_label = QtWidgets.QLabel(self.widget1)
        self.WeightScaling_label.setObjectName("WeightScaling_label")
        self.verticalLayout_5.addWidget(self.WeightScaling_label)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(1230, 20, 159, 22))
        self.comboBox.setMaxVisibleItems(50)
        self.comboBox.setObjectName("comboBox")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 10, 21, 921))
        self.line.setMaximumSize(QtCore.QSize(21, 16777215))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.saveFileButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.saveFileButton_2.setGeometry(QtCore.QRect(200, 30, 121, 23))
        self.saveFileButton_2.setObjectName("saveFileButton_2")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(1270, 900, 120, 23))
        self.exitButton.setObjectName("exitButton")
        self.openFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.openFileButton.setGeometry(QtCore.QRect(80, 30, 120, 23))
        self.openFileButton.setObjectName("openFileButton")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(10, 923, 1391, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(1390, 10, 21, 921))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.fileName = QtWidgets.QLabel(self.centralwidget)
        self.fileName.setGeometry(QtCore.QRect(330, 30, 261, 16))
        self.fileName.setText("")
        self.fileName.setObjectName("fileName")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, -10, 1391, 41))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.loadedCount = QtWidgets.QLCDNumber(self.centralwidget)
        self.loadedCount.setEnabled(True)
        self.loadedCount.setGeometry(QtCore.QRect(1140, 20, 64, 23))
        self.loadedCount.setAutoFillBackground(False)
        self.loadedCount.setObjectName("loadedCount")
        self.A = QtWidgets.QGroupBox(self.centralwidget)
        self.A.setGeometry(QtCore.QRect(270, 58, 271, 851))
        self.A.setObjectName("A")
        self.widget2 = QtWidgets.QWidget(self.A)
        self.widget2.setGeometry(QtCore.QRect(6, 30, 102, 721))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.CritBase_label = QtWidgets.QLabel(self.widget2)
        self.CritBase_label.setObjectName("CritBase_label")
        self.verticalLayout_6.addWidget(self.CritBase_label)
        self.CritScaling_label = QtWidgets.QLabel(self.widget2)
        self.CritScaling_label.setObjectName("CritScaling_label")
        self.verticalLayout_6.addWidget(self.CritScaling_label)
        self.KBBase_label = QtWidgets.QLabel(self.widget2)
        self.KBBase_label.setObjectName("KBBase_label")
        self.verticalLayout_6.addWidget(self.KBBase_label)
        self.KBScaling_label = QtWidgets.QLabel(self.widget2)
        self.KBScaling_label.setObjectName("KBScaling_label")
        self.verticalLayout_6.addWidget(self.KBScaling_label)
        self.label = QtWidgets.QLabel(self.widget2)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.FireRate_label = QtWidgets.QLabel(self.widget2)
        self.FireRate_label.setObjectName("FireRate_label")
        self.verticalLayout_6.addWidget(self.FireRate_label)
        self.FireRateScaling_label = QtWidgets.QLabel(self.widget2)
        self.FireRateScaling_label.setObjectName("FireRateScaling_label")
        self.verticalLayout_6.addWidget(self.FireRateScaling_label)
        self.SleepRate_label = QtWidgets.QLabel(self.widget2)
        self.SleepRate_label.setObjectName("SleepRate_label")
        self.verticalLayout_6.addWidget(self.SleepRate_label)
        self.SleepRateScaling_label = QtWidgets.QLabel(self.widget2)
        self.SleepRateScaling_label.setObjectName("SleepRateScaling_label")
        self.verticalLayout_6.addWidget(self.SleepRateScaling_label)
        self.FreezeRate_label = QtWidgets.QLabel(self.widget2)
        self.FreezeRate_label.setObjectName("FreezeRate_label")
        self.verticalLayout_6.addWidget(self.FreezeRate_label)
        self.FreezeRateScaling_2 = QtWidgets.QLabel(self.widget2)
        self.FreezeRateScaling_2.setObjectName("FreezeRateScaling_2")
        self.verticalLayout_6.addWidget(self.FreezeRateScaling_2)
        self.PoisonRate_label = QtWidgets.QLabel(self.widget2)
        self.PoisonRate_label.setObjectName("PoisonRate_label")
        self.verticalLayout_6.addWidget(self.PoisonRate_label)
        self.PoisonRateScaling_label = QtWidgets.QLabel(self.widget2)
        self.PoisonRateScaling_label.setObjectName("PoisonRateScaling_label")
        self.verticalLayout_6.addWidget(self.PoisonRateScaling_label)
        self.CritRes_label = QtWidgets.QLabel(self.widget2)
        self.CritRes_label.setObjectName("CritRes_label")
        self.verticalLayout_6.addWidget(self.CritRes_label)
        self.CritResScaling_label = QtWidgets.QLabel(self.widget2)
        self.CritResScaling_label.setObjectName("CritResScaling_label")
        self.verticalLayout_6.addWidget(self.CritResScaling_label)
        self.KBRes_label = QtWidgets.QLabel(self.widget2)
        self.KBRes_label.setObjectName("KBRes_label")
        self.verticalLayout_6.addWidget(self.KBRes_label)
        self.KBResScaling_label = QtWidgets.QLabel(self.widget2)
        self.KBResScaling_label.setObjectName("KBResScaling_label")
        self.verticalLayout_6.addWidget(self.KBResScaling_label)
        self.StaggerRes_lebel = QtWidgets.QLabel(self.widget2)
        self.StaggerRes_lebel.setObjectName("StaggerRes_lebel")
        self.verticalLayout_6.addWidget(self.StaggerRes_lebel)
        self.StaggerResScaling_label = QtWidgets.QLabel(self.widget2)
        self.StaggerResScaling_label.setObjectName("StaggerResScaling_label")
        self.verticalLayout_6.addWidget(self.StaggerResScaling_label)
        self.FireRes_label = QtWidgets.QLabel(self.widget2)
        self.FireRes_label.setObjectName("FireRes_label")
        self.verticalLayout_6.addWidget(self.FireRes_label)
        self.label_17 = QtWidgets.QLabel(self.widget2)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_6.addWidget(self.label_17)
        self.SleepRes_label = QtWidgets.QLabel(self.widget2)
        self.SleepRes_label.setObjectName("SleepRes_label")
        self.verticalLayout_6.addWidget(self.SleepRes_label)
        self.SleepResScaling_label = QtWidgets.QLabel(self.widget2)
        self.SleepResScaling_label.setObjectName("SleepResScaling_label")
        self.verticalLayout_6.addWidget(self.SleepResScaling_label)
        self.FreezeRes_label = QtWidgets.QLabel(self.widget2)
        self.FreezeRes_label.setObjectName("FreezeRes_label")
        self.verticalLayout_6.addWidget(self.FreezeRes_label)
        self.FreezeResScaling_label = QtWidgets.QLabel(self.widget2)
        self.FreezeResScaling_label.setObjectName("FreezeResScaling_label")
        self.verticalLayout_6.addWidget(self.FreezeResScaling_label)
        self.PoisonRes_label = QtWidgets.QLabel(self.widget2)
        self.PoisonRes_label.setObjectName("PoisonRes_label")
        self.verticalLayout_6.addWidget(self.PoisonRes_label)
        self.PoisonResScaling_label = QtWidgets.QLabel(self.widget2)
        self.PoisonResScaling_label.setObjectName("PoisonResScaling_label")
        self.verticalLayout_6.addWidget(self.PoisonResScaling_label)
        self.widget3 = QtWidgets.QWidget(self.A)
        self.widget3.setGeometry(QtCore.QRect(110, 29, 135, 724))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.CritBase = QtWidgets.QLineEdit(self.widget3)
        self.CritBase.setReadOnly(True)
        self.CritBase.setObjectName("CritBase")
        self.verticalLayout_7.addWidget(self.CritBase)
        self.CritScaling = QtWidgets.QLineEdit(self.widget3)
        self.CritScaling.setReadOnly(True)
        self.CritScaling.setObjectName("CritScaling")
        self.verticalLayout_7.addWidget(self.CritScaling)
        self.KBBase = QtWidgets.QLineEdit(self.widget3)
        self.KBBase.setReadOnly(True)
        self.KBBase.setObjectName("KBBase")
        self.verticalLayout_7.addWidget(self.KBBase)
        self.KBScaling = QtWidgets.QLineEdit(self.widget3)
        self.KBScaling.setReadOnly(True)
        self.KBScaling.setObjectName("KBScaling")
        self.verticalLayout_7.addWidget(self.KBScaling)
        self.StaggerRate = QtWidgets.QLineEdit(self.widget3)
        self.StaggerRate.setReadOnly(True)
        self.StaggerRate.setObjectName("StaggerRate")
        self.verticalLayout_7.addWidget(self.StaggerRate)
        self.StaggerRateScaling = QtWidgets.QLineEdit(self.widget3)
        self.StaggerRateScaling.setReadOnly(True)
        self.StaggerRateScaling.setObjectName("StaggerRateScaling")
        self.verticalLayout_7.addWidget(self.StaggerRateScaling)
        self.FireRate = QtWidgets.QLineEdit(self.widget3)
        self.FireRate.setText("")
        self.FireRate.setReadOnly(True)
        self.FireRate.setObjectName("FireRate")
        self.verticalLayout_7.addWidget(self.FireRate)
        self.FireRateScaling = QtWidgets.QLineEdit(self.widget3)
        self.FireRateScaling.setReadOnly(True)
        self.FireRateScaling.setObjectName("FireRateScaling")
        self.verticalLayout_7.addWidget(self.FireRateScaling)
        self.SleepRate = QtWidgets.QLineEdit(self.widget3)
        self.SleepRate.setReadOnly(True)
        self.SleepRate.setObjectName("SleepRate")
        self.verticalLayout_7.addWidget(self.SleepRate)
        self.SleepRateScaling = QtWidgets.QLineEdit(self.widget3)
        self.SleepRateScaling.setReadOnly(True)
        self.SleepRateScaling.setObjectName("SleepRateScaling")
        self.verticalLayout_7.addWidget(self.SleepRateScaling)
        self.FreezeRate = QtWidgets.QLineEdit(self.widget3)
        self.FreezeRate.setReadOnly(True)
        self.FreezeRate.setObjectName("FreezeRate")
        self.verticalLayout_7.addWidget(self.FreezeRate)
        self.FreezeRateScaling = QtWidgets.QLineEdit(self.widget3)
        self.FreezeRateScaling.setReadOnly(True)
        self.FreezeRateScaling.setObjectName("FreezeRateScaling")
        self.verticalLayout_7.addWidget(self.FreezeRateScaling)
        self.PoisonRate = QtWidgets.QLineEdit(self.widget3)
        self.PoisonRate.setReadOnly(True)
        self.PoisonRate.setObjectName("PoisonRate")
        self.verticalLayout_7.addWidget(self.PoisonRate)
        self.PoisonRateScaling = QtWidgets.QLineEdit(self.widget3)
        self.PoisonRateScaling.setReadOnly(True)
        self.PoisonRateScaling.setObjectName("PoisonRateScaling")
        self.verticalLayout_7.addWidget(self.PoisonRateScaling)
        self.CritRes = QtWidgets.QLineEdit(self.widget3)
        self.CritRes.setReadOnly(True)
        self.CritRes.setObjectName("CritRes")
        self.verticalLayout_7.addWidget(self.CritRes)
        self.CritResScaling = QtWidgets.QLineEdit(self.widget3)
        self.CritResScaling.setReadOnly(True)
        self.CritResScaling.setObjectName("CritResScaling")
        self.verticalLayout_7.addWidget(self.CritResScaling)
        self.KBRes = QtWidgets.QLineEdit(self.widget3)
        self.KBRes.setReadOnly(True)
        self.KBRes.setObjectName("KBRes")
        self.verticalLayout_7.addWidget(self.KBRes)
        self.KBResScaling = QtWidgets.QLineEdit(self.widget3)
        self.KBResScaling.setReadOnly(True)
        self.KBResScaling.setObjectName("KBResScaling")
        self.verticalLayout_7.addWidget(self.KBResScaling)
        self.StaggerRes = QtWidgets.QLineEdit(self.widget3)
        self.StaggerRes.setReadOnly(True)
        self.StaggerRes.setObjectName("StaggerRes")
        self.verticalLayout_7.addWidget(self.StaggerRes)
        self.StaggerResScaling = QtWidgets.QLineEdit(self.widget3)
        self.StaggerResScaling.setObjectName("StaggerResScaling")
        self.verticalLayout_7.addWidget(self.StaggerResScaling)
        self.FireRes = QtWidgets.QLineEdit(self.widget3)
        self.FireRes.setReadOnly(True)
        self.FireRes.setObjectName("FireRes")
        self.verticalLayout_7.addWidget(self.FireRes)
        self.FireResScaling = QtWidgets.QLineEdit(self.widget3)
        self.FireResScaling.setReadOnly(True)
        self.FireResScaling.setObjectName("FireResScaling")
        self.verticalLayout_7.addWidget(self.FireResScaling)
        self.SleepRes = QtWidgets.QLineEdit(self.widget3)
        self.SleepRes.setReadOnly(True)
        self.SleepRes.setObjectName("SleepRes")
        self.verticalLayout_7.addWidget(self.SleepRes)
        self.SleepResScaling = QtWidgets.QLineEdit(self.widget3)
        self.SleepResScaling.setReadOnly(True)
        self.SleepResScaling.setObjectName("SleepResScaling")
        self.verticalLayout_7.addWidget(self.SleepResScaling)
        self.FreezeRes = QtWidgets.QLineEdit(self.widget3)
        self.FreezeRes.setReadOnly(True)
        self.FreezeRes.setObjectName("FreezeRes")
        self.verticalLayout_7.addWidget(self.FreezeRes)
        self.FreezeResScaling = QtWidgets.QLineEdit(self.widget3)
        self.FreezeResScaling.setReadOnly(True)
        self.FreezeResScaling.setObjectName("FreezeResScaling")
        self.verticalLayout_7.addWidget(self.FreezeResScaling)
        self.PoisonRes = QtWidgets.QLineEdit(self.widget3)
        self.PoisonRes.setReadOnly(True)
        self.PoisonRes.setObjectName("PoisonRes")
        self.verticalLayout_7.addWidget(self.PoisonRes)
        self.PoisonResScaling = QtWidgets.QLineEdit(self.widget3)
        self.PoisonResScaling.setReadOnly(True)
        self.PoisonResScaling.setObjectName("PoisonResScaling")
        self.verticalLayout_7.addWidget(self.PoisonResScaling)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(570, 58, 251, 851))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 30, 151, 541))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.DemonsX = QtWidgets.QLineEdit(self.layoutWidget)
        self.DemonsX.setReadOnly(True)
        self.DemonsX.setObjectName("DemonsX")
        self.verticalLayout_2.addWidget(self.DemonsX)
        self.DemonsXScaling = QtWidgets.QLineEdit(self.layoutWidget)
        self.DemonsXScaling.setReadOnly(True)
        self.DemonsXScaling.setObjectName("DemonsXScaling")
        self.verticalLayout_2.addWidget(self.DemonsXScaling)
        self.UndeadX = QtWidgets.QLineEdit(self.layoutWidget)
        self.UndeadX.setReadOnly(True)
        self.UndeadX.setObjectName("UndeadX")
        self.verticalLayout_2.addWidget(self.UndeadX)
        self.UndeadXScaling = QtWidgets.QLineEdit(self.layoutWidget)
        self.UndeadXScaling.setReadOnly(True)
        self.UndeadXScaling.setObjectName("UndeadXScaling")
        self.verticalLayout_2.addWidget(self.UndeadXScaling)
        self.ShellsX = QtWidgets.QLineEdit(self.layoutWidget)
        self.ShellsX.setReadOnly(True)
        self.ShellsX.setObjectName("ShellsX")
        self.verticalLayout_2.addWidget(self.ShellsX)
        self.ShellsXScaling = QtWidgets.QLineEdit(self.layoutWidget)
        self.ShellsXScaling.setReadOnly(True)
        self.ShellsXScaling.setObjectName("ShellsXScaling")
        self.verticalLayout_2.addWidget(self.ShellsXScaling)
        self.DragonsX = QtWidgets.QLineEdit(self.layoutWidget)
        self.DragonsX.setReadOnly(True)
        self.DragonsX.setObjectName("DragonsX")
        self.verticalLayout_2.addWidget(self.DragonsX)
        self.DragonsXScaling = QtWidgets.QLineEdit(self.layoutWidget)
        self.DragonsXScaling.setReadOnly(True)
        self.DragonsXScaling.setObjectName("DragonsXScaling")
        self.verticalLayout_2.addWidget(self.DragonsXScaling)
        self.GiantsX = QtWidgets.QLineEdit(self.layoutWidget)
        self.GiantsX.setReadOnly(True)
        self.GiantsX.setObjectName("GiantsX")
        self.verticalLayout_2.addWidget(self.GiantsX)
        self.GiantsXScaling = QtWidgets.QLineEdit(self.layoutWidget)
        self.GiantsXScaling.setReadOnly(True)
        self.GiantsXScaling.setObjectName("GiantsXScaling")
        self.verticalLayout_2.addWidget(self.GiantsXScaling)
        self.WoodX = QtWidgets.QLineEdit(self.layoutWidget)
        self.WoodX.setReadOnly(True)
        self.WoodX.setObjectName("WoodX")
        self.verticalLayout_2.addWidget(self.WoodX)
        self.WoodXScaling = QtWidgets.QLineEdit(self.layoutWidget)
        self.WoodXScaling.setReadOnly(True)
        self.WoodXScaling.setObjectName("WoodXScaling")
        self.verticalLayout_2.addWidget(self.WoodXScaling)
        self.StoneX = QtWidgets.QLineEdit(self.layoutWidget)
        self.StoneX.setReadOnly(True)
        self.StoneX.setObjectName("StoneX")
        self.verticalLayout_2.addWidget(self.StoneX)
        self.StoneXScaling = QtWidgets.QLineEdit(self.layoutWidget)
        self.StoneXScaling.setText("")
        self.StoneXScaling.setReadOnly(True)
        self.StoneXScaling.setObjectName("StoneXScaling")
        self.verticalLayout_2.addWidget(self.StoneXScaling)
        self.MetalsX = QtWidgets.QLineEdit(self.layoutWidget)
        self.MetalsX.setReadOnly(True)
        self.MetalsX.setObjectName("MetalsX")
        self.verticalLayout_2.addWidget(self.MetalsX)
        self.MetalsXScaling = QtWidgets.QLineEdit(self.layoutWidget)
        self.MetalsXScaling.setReadOnly(True)
        self.MetalsXScaling.setObjectName("MetalsXScaling")
        self.verticalLayout_2.addWidget(self.MetalsXScaling)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 35, 87, 521))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.DemonsX_label = QtWidgets.QLabel(self.layoutWidget1)
        self.DemonsX_label.setObjectName("DemonsX_label")
        self.verticalLayout_3.addWidget(self.DemonsX_label)
        self.DemonsXScaling_label = QtWidgets.QLabel(self.layoutWidget1)
        self.DemonsXScaling_label.setObjectName("DemonsXScaling_label")
        self.verticalLayout_3.addWidget(self.DemonsXScaling_label)
        self.UndeadX_label = QtWidgets.QLabel(self.layoutWidget1)
        self.UndeadX_label.setObjectName("UndeadX_label")
        self.verticalLayout_3.addWidget(self.UndeadX_label)
        self.UndeadXScaling_label = QtWidgets.QLabel(self.layoutWidget1)
        self.UndeadXScaling_label.setObjectName("UndeadXScaling_label")
        self.verticalLayout_3.addWidget(self.UndeadXScaling_label)
        self.ShellsX_label = QtWidgets.QLabel(self.layoutWidget1)
        self.ShellsX_label.setObjectName("ShellsX_label")
        self.verticalLayout_3.addWidget(self.ShellsX_label)
        self.ShellsXScaling_label = QtWidgets.QLabel(self.layoutWidget1)
        self.ShellsXScaling_label.setObjectName("ShellsXScaling_label")
        self.verticalLayout_3.addWidget(self.ShellsXScaling_label)
        self.DragonsX_label = QtWidgets.QLabel(self.layoutWidget1)
        self.DragonsX_label.setObjectName("DragonsX_label")
        self.verticalLayout_3.addWidget(self.DragonsX_label)
        self.DragonsXScaling_label = QtWidgets.QLabel(self.layoutWidget1)
        self.DragonsXScaling_label.setObjectName("DragonsXScaling_label")
        self.verticalLayout_3.addWidget(self.DragonsXScaling_label)
        self.GiantsX_label = QtWidgets.QLabel(self.layoutWidget1)
        self.GiantsX_label.setObjectName("GiantsX_label")
        self.verticalLayout_3.addWidget(self.GiantsX_label)
        self.GiantsXScaling_label = QtWidgets.QLabel(self.layoutWidget1)
        self.GiantsXScaling_label.setObjectName("GiantsXScaling_label")
        self.verticalLayout_3.addWidget(self.GiantsXScaling_label)
        self.WoodX_label = QtWidgets.QLabel(self.layoutWidget1)
        self.WoodX_label.setObjectName("WoodX_label")
        self.verticalLayout_3.addWidget(self.WoodX_label)
        self.WoodXScaling_label = QtWidgets.QLabel(self.layoutWidget1)
        self.WoodXScaling_label.setObjectName("WoodXScaling_label")
        self.verticalLayout_3.addWidget(self.WoodXScaling_label)
        self.StoneX_label = QtWidgets.QLabel(self.layoutWidget1)
        self.StoneX_label.setObjectName("StoneX_label")
        self.verticalLayout_3.addWidget(self.StoneX_label)
        self.StoneXScaling_label = QtWidgets.QLabel(self.layoutWidget1)
        self.StoneXScaling_label.setObjectName("StoneXScaling_label")
        self.verticalLayout_3.addWidget(self.StoneXScaling_label)
        self.MetalsX_label = QtWidgets.QLabel(self.layoutWidget1)
        self.MetalsX_label.setObjectName("MetalsX_label")
        self.verticalLayout_3.addWidget(self.MetalsX_label)
        self.MetalsXScaling_label = QtWidgets.QLabel(self.layoutWidget1)
        self.MetalsXScaling_label.setObjectName("MetalsXScaling_label")
        self.verticalLayout_3.addWidget(self.MetalsXScaling_label)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(821, 58, 201, 851))
        self.groupBox_3.setObjectName("groupBox_3")
        self.splitter_5 = QtWidgets.QSplitter(self.groupBox_3)
        self.splitter_5.setGeometry(QtCore.QRect(10, 30, 40, 331))
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.SlashX_label = QtWidgets.QLabel(self.splitter_5)
        self.SlashX_label.setObjectName("SlashX_label")
        self.StrikeX_label = QtWidgets.QLabel(self.splitter_5)
        self.StrikeX_label.setObjectName("StrikeX_label")
        self.label_13 = QtWidgets.QLabel(self.splitter_5)
        self.label_13.setObjectName("label_13")
        self.CrushX_label = QtWidgets.QLabel(self.splitter_5)
        self.CrushX_label.setObjectName("CrushX_label")
        self.label_14 = QtWidgets.QLabel(self.splitter_5)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.splitter_5)
        self.label_15.setObjectName("label_15")
        self.ShockX_label = QtWidgets.QLabel(self.splitter_5)
        self.ShockX_label.setObjectName("ShockX_label")
        self.PoisonX_label = QtWidgets.QLabel(self.splitter_5)
        self.PoisonX_label.setObjectName("PoisonX_label")
        self.SoundX_label = QtWidgets.QLabel(self.splitter_5)
        self.SoundX_label.setObjectName("SoundX_label")
        self.label_16 = QtWidgets.QLabel(self.splitter_5)
        self.label_16.setObjectName("label_16")
        self.DarkX_label = QtWidgets.QLabel(self.splitter_5)
        self.DarkX_label.setObjectName("DarkX_label")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(61, 29, 135, 331))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.SlashX = QtWidgets.QLineEdit(self.layoutWidget2)
        self.SlashX.setReadOnly(True)
        self.SlashX.setObjectName("SlashX")
        self.verticalLayout_4.addWidget(self.SlashX)
        self.StrikeX = QtWidgets.QLineEdit(self.layoutWidget2)
        self.StrikeX.setReadOnly(True)
        self.StrikeX.setObjectName("StrikeX")
        self.verticalLayout_4.addWidget(self.StrikeX)
        self.StabX = QtWidgets.QLineEdit(self.layoutWidget2)
        self.StabX.setReadOnly(True)
        self.StabX.setObjectName("StabX")
        self.verticalLayout_4.addWidget(self.StabX)
        self.CrushX = QtWidgets.QLineEdit(self.layoutWidget2)
        self.CrushX.setReadOnly(True)
        self.CrushX.setObjectName("CrushX")
        self.verticalLayout_4.addWidget(self.CrushX)
        self.FlameX = QtWidgets.QLineEdit(self.layoutWidget2)
        self.FlameX.setReadOnly(True)
        self.FlameX.setObjectName("FlameX")
        self.verticalLayout_4.addWidget(self.FlameX)
        self.IceX = QtWidgets.QLineEdit(self.layoutWidget2)
        self.IceX.setReadOnly(True)
        self.IceX.setObjectName("IceX")
        self.verticalLayout_4.addWidget(self.IceX)
        self.ShockX = QtWidgets.QLineEdit(self.layoutWidget2)
        self.ShockX.setReadOnly(True)
        self.ShockX.setObjectName("ShockX")
        self.verticalLayout_4.addWidget(self.ShockX)
        self.PoisonX = QtWidgets.QLineEdit(self.layoutWidget2)
        self.PoisonX.setText("")
        self.PoisonX.setReadOnly(True)
        self.PoisonX.setObjectName("PoisonX")
        self.verticalLayout_4.addWidget(self.PoisonX)
        self.SoundX = QtWidgets.QLineEdit(self.layoutWidget2)
        self.SoundX.setReadOnly(True)
        self.SoundX.setObjectName("SoundX")
        self.verticalLayout_4.addWidget(self.SoundX)
        self.LightX = QtWidgets.QLineEdit(self.layoutWidget2)
        self.LightX.setReadOnly(True)
        self.LightX.setObjectName("LightX")
        self.verticalLayout_4.addWidget(self.LightX)
        self.DarkX = QtWidgets.QLineEdit(self.layoutWidget2)
        self.DarkX.setReadOnly(True)
        self.DarkX.setObjectName("DarkX")
        self.verticalLayout_4.addWidget(self.DarkX)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(1020, 58, 201, 171))
        self.groupBox_4.setObjectName("groupBox_4")
        self.Crush = QtWidgets.QCheckBox(self.groupBox_4)
        self.Crush.setGeometry(QtCore.QRect(10, 90, 70, 17))
        self.Crush.setCheckable(False)
        self.Crush.setObjectName("Crush")
        self.Slash = QtWidgets.QCheckBox(self.groupBox_4)
        self.Slash.setGeometry(QtCore.QRect(10, 30, 70, 17))
        self.Slash.setCheckable(False)
        self.Slash.setObjectName("Slash")
        self.Strike = QtWidgets.QCheckBox(self.groupBox_4)
        self.Strike.setGeometry(QtCore.QRect(10, 50, 70, 17))
        self.Strike.setCheckable(False)
        self.Strike.setChecked(False)
        self.Strike.setObjectName("Strike")
        self.Stab = QtWidgets.QCheckBox(self.groupBox_4)
        self.Stab.setGeometry(QtCore.QRect(10, 70, 70, 17))
        self.Stab.setCheckable(False)
        self.Stab.setChecked(False)
        self.Stab.setObjectName("Stab")
        self.Fire = QtWidgets.QCheckBox(self.groupBox_4)
        self.Fire.setGeometry(QtCore.QRect(10, 110, 70, 17))
        self.Fire.setCheckable(False)
        self.Fire.setChecked(False)
        self.Fire.setObjectName("Fire")
        self.Ice = QtWidgets.QCheckBox(self.groupBox_4)
        self.Ice.setGeometry(QtCore.QRect(10, 130, 70, 17))
        self.Ice.setCheckable(False)
        self.Ice.setChecked(False)
        self.Ice.setObjectName("Ice")
        self.Lightning = QtWidgets.QCheckBox(self.groupBox_4)
        self.Lightning.setGeometry(QtCore.QRect(10, 150, 61, 17))
        self.Lightning.setCheckable(False)
        self.Lightning.setChecked(False)
        self.Lightning.setObjectName("Lightning")
        self.Poison = QtWidgets.QCheckBox(self.groupBox_4)
        self.Poison.setGeometry(QtCore.QRect(90, 30, 70, 17))
        self.Poison.setCheckable(False)
        self.Poison.setChecked(False)
        self.Poison.setObjectName("Poison")
        self.Sound = QtWidgets.QCheckBox(self.groupBox_4)
        self.Sound.setGeometry(QtCore.QRect(90, 50, 70, 17))
        self.Sound.setCheckable(False)
        self.Sound.setChecked(False)
        self.Sound.setObjectName("Sound")
        self.Light = QtWidgets.QCheckBox(self.groupBox_4)
        self.Light.setGeometry(QtCore.QRect(90, 70, 70, 17))
        self.Light.setCheckable(False)
        self.Light.setChecked(False)
        self.Light.setObjectName("Light")
        self.Darkness = QtWidgets.QCheckBox(self.groupBox_4)
        self.Darkness.setGeometry(QtCore.QRect(90, 90, 70, 17))
        self.Darkness.setCheckable(False)
        self.Darkness.setChecked(False)
        self.Darkness.setObjectName("Darkness")
        self.Burn = QtWidgets.QCheckBox(self.groupBox_4)
        self.Burn.setGeometry(QtCore.QRect(90, 110, 70, 17))
        self.Burn.setCheckable(False)
        self.Burn.setChecked(False)
        self.Burn.setObjectName("Burn")
        self.Venom = QtWidgets.QCheckBox(self.groupBox_4)
        self.Venom.setGeometry(QtCore.QRect(90, 130, 70, 17))
        self.Venom.setCheckable(False)
        self.Venom.setChecked(False)
        self.Venom.setObjectName("Venom")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(1020, 230, 201, 221))
        self.groupBox_5.setObjectName("groupBox_5")
        self.CritImm = QtWidgets.QCheckBox(self.groupBox_5)
        self.CritImm.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.CritImm.setCheckable(False)
        self.CritImm.setObjectName("CritImm")
        self.PoisonImm = QtWidgets.QCheckBox(self.groupBox_5)
        self.PoisonImm.setGeometry(QtCore.QRect(10, 140, 81, 17))
        self.PoisonImm.setCheckable(False)
        self.PoisonImm.setObjectName("PoisonImm")
        self.FireImm = QtWidgets.QCheckBox(self.groupBox_5)
        self.FireImm.setGeometry(QtCore.QRect(10, 80, 70, 17))
        self.FireImm.setCheckable(False)
        self.FireImm.setObjectName("FireImm")
        self.StaggerImm = QtWidgets.QCheckBox(self.groupBox_5)
        self.StaggerImm.setGeometry(QtCore.QRect(10, 40, 81, 17))
        self.StaggerImm.setCheckable(False)
        self.StaggerImm.setObjectName("StaggerImm")
        self.SleepImm = QtWidgets.QCheckBox(self.groupBox_5)
        self.SleepImm.setGeometry(QtCore.QRect(10, 100, 70, 17))
        self.SleepImm.setCheckable(False)
        self.SleepImm.setObjectName("SleepImm")
        self.TumbleImm = QtWidgets.QCheckBox(self.groupBox_5)
        self.TumbleImm.setGeometry(QtCore.QRect(10, 160, 81, 17))
        self.TumbleImm.setCheckable(False)
        self.TumbleImm.setObjectName("TumbleImm")
        self.KBImm = QtWidgets.QCheckBox(self.groupBox_5)
        self.KBImm.setGeometry(QtCore.QRect(10, 56, 70, 21))
        self.KBImm.setCheckable(False)
        self.KBImm.setObjectName("KBImm")
        self.IceImm = QtWidgets.QCheckBox(self.groupBox_5)
        self.IceImm.setGeometry(QtCore.QRect(10, 120, 70, 17))
        self.IceImm.setCheckable(False)
        self.IceImm.setObjectName("IceImm")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1060, 900, 311, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1030, 520, 271, 351))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1424, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Potapon Resource File Editor"))
        self.groupBox.setTitle(_translate("MainWindow", "BaseStats"))
        self.HPBase_label.setText(_translate("MainWindow", "HP Base"))
        self.HPScaling_label.setText(_translate("MainWindow", "HP Scaling"))
        self.labelFeverSpeed_label.setText(_translate("MainWindow", "Fever Speed"))
        self.AttackSpeed_label.setText(_translate("MainWindow", "Attack Speed"))
        self.SprintSpeed_label.setText(_translate("MainWindow", "Sprint Speed"))
        self.MinDMG_label.setText(_translate("MainWindow", "Min DMG"))
        self.MinDMGScaling_label.setText(_translate("MainWindow", "Min DMG Scaling"))
        self.MaxDMG_label.setText(_translate("MainWindow", "MaxDMG"))
        self.MaxDMGScaling_label.setText(_translate("MainWindow", "Max DMG Scaling"))
        self.Power_label.setText(_translate("MainWindow", "Power"))
        self.PowerScaling_label.setText(_translate("MainWindow", "Power Scaling"))
        self.ShieldBreak_label.setText(_translate("MainWindow", "Shield Break"))
        self.ShieldBreakScaling_label.setText(_translate("MainWindow", "Shield Break Scaling"))
        self.Defense_label.setText(_translate("MainWindow", "Defense"))
        self.DefenseScaling_label.setText(_translate("MainWindow", "Defense Scaling"))
        self.Evasion_label.setText(_translate("MainWindow", "Evasion"))
        self.EvasionScaling_label.setText(_translate("MainWindow", "Evasion Scaling"))
        self.Weight_label.setText(_translate("MainWindow", "Weight"))
        self.WeightScaling_label.setText(_translate("MainWindow", "Weight Scaling"))
        self.saveFileButton_2.setText(_translate("MainWindow", "Сохранить файл"))
        self.exitButton.setText(_translate("MainWindow", "Выход"))
        self.openFileButton.setText(_translate("MainWindow", " Открыть файл"))
        self.A.setTitle(_translate("MainWindow", "Status Effects"))
        self.CritBase_label.setText(_translate("MainWindow", "Crit Base"))
        self.CritScaling_label.setText(_translate("MainWindow", "Crit Scaling"))
        self.KBBase_label.setText(_translate("MainWindow", "KB Base"))
        self.KBScaling_label.setText(_translate("MainWindow", "KB Scaling"))
        self.label.setText(_translate("MainWindow", "Stagger Rate"))
        self.label_2.setText(_translate("MainWindow", "Stagger Rate Scaling"))
        self.FireRate_label.setText(_translate("MainWindow", "Fire Rate"))
        self.FireRateScaling_label.setText(_translate("MainWindow", "Fire Rate Scaling"))
        self.SleepRate_label.setText(_translate("MainWindow", "Sleep Rate"))
        self.SleepRateScaling_label.setText(_translate("MainWindow", "Sleep Rate Scaling"))
        self.FreezeRate_label.setText(_translate("MainWindow", "Freeze Rate"))
        self.FreezeRateScaling_2.setText(_translate("MainWindow", "Freeze Rate Scaling"))
        self.PoisonRate_label.setText(_translate("MainWindow", "Poison Rate"))
        self.PoisonRateScaling_label.setText(_translate("MainWindow", "Poison Rate Scaling"))
        self.CritRes_label.setText(_translate("MainWindow", "Crit Res"))
        self.CritResScaling_label.setText(_translate("MainWindow", "Crit Res Scaling"))
        self.KBRes_label.setText(_translate("MainWindow", "KB Res"))
        self.KBResScaling_label.setText(_translate("MainWindow", "KB Res Scaling"))
        self.StaggerRes_lebel.setText(_translate("MainWindow", "Stagger Res"))
        self.StaggerResScaling_label.setText(_translate("MainWindow", "Stagger Res Scaling"))
        self.FireRes_label.setText(_translate("MainWindow", "Fire Res"))
        self.label_17.setText(_translate("MainWindow", "Fire Res Scaling"))
        self.SleepRes_label.setText(_translate("MainWindow", "Sleep Res"))
        self.SleepResScaling_label.setText(_translate("MainWindow", "Sleep Res Scaling"))
        self.FreezeRes_label.setText(_translate("MainWindow", "Freeze Res"))
        self.FreezeResScaling_label.setText(_translate("MainWindow", "Freeze Res Scaling"))
        self.PoisonRes_label.setText(_translate("MainWindow", "Poison Res"))
        self.PoisonResScaling_label.setText(_translate("MainWindow", "Poison Res Scaling"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Damage Multipliers"))
        self.DemonsX_label.setText(_translate("MainWindow", "Demons X"))
        self.DemonsXScaling_label.setText(_translate("MainWindow", "Demons X Scaling"))
        self.UndeadX_label.setText(_translate("MainWindow", "Undead X"))
        self.UndeadXScaling_label.setText(_translate("MainWindow", "Undead X Scaling"))
        self.ShellsX_label.setText(_translate("MainWindow", "Shells X"))
        self.ShellsXScaling_label.setText(_translate("MainWindow", "Shells X Scaling"))
        self.DragonsX_label.setText(_translate("MainWindow", "Dragons X"))
        self.DragonsXScaling_label.setText(_translate("MainWindow", "Dragons X Scaling"))
        self.GiantsX_label.setText(_translate("MainWindow", "Giants X"))
        self.GiantsXScaling_label.setText(_translate("MainWindow", "Giants X Scaling"))
        self.WoodX_label.setText(_translate("MainWindow", "Wood X"))
        self.WoodXScaling_label.setText(_translate("MainWindow", "Wood X Scaling"))
        self.StoneX_label.setText(_translate("MainWindow", "Stone X"))
        self.StoneXScaling_label.setText(_translate("MainWindow", "Stone X Scaling"))
        self.MetalsX_label.setText(_translate("MainWindow", "Metals X"))
        self.MetalsXScaling_label.setText(_translate("MainWindow", "MetalsX Scaling"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Resistance Multipliers"))
        self.SlashX_label.setText(_translate("MainWindow", "Slash X"))
        self.StrikeX_label.setText(_translate("MainWindow", "Strike X"))
        self.label_13.setText(_translate("MainWindow", "Stab X"))
        self.CrushX_label.setText(_translate("MainWindow", "Crush X"))
        self.label_14.setText(_translate("MainWindow", "Flame X"))
        self.label_15.setText(_translate("MainWindow", "Ice X"))
        self.ShockX_label.setText(_translate("MainWindow", "Shock X"))
        self.PoisonX_label.setText(_translate("MainWindow", "Poison X"))
        self.SoundX_label.setText(_translate("MainWindow", "Sound X"))
        self.label_16.setText(_translate("MainWindow", "Light X"))
        self.DarkX_label.setText(_translate("MainWindow", "Dark X"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Attack Elements"))
        self.Crush.setText(_translate("MainWindow", "Crush"))
        self.Slash.setText(_translate("MainWindow", " Slash"))
        self.Strike.setText(_translate("MainWindow", "Strike"))
        self.Stab.setText(_translate("MainWindow", "Stab"))
        self.Fire.setText(_translate("MainWindow", "Fire"))
        self.Ice.setText(_translate("MainWindow", "Ice"))
        self.Lightning.setText(_translate("MainWindow", "Lightning"))
        self.Poison.setText(_translate("MainWindow", "Poison"))
        self.Sound.setText(_translate("MainWindow", "Sound"))
        self.Light.setText(_translate("MainWindow", " Light"))
        self.Darkness.setText(_translate("MainWindow", "Darkness"))
        self.Burn.setText(_translate("MainWindow", "Burn"))
        self.Venom.setText(_translate("MainWindow", "Venom"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Status Immunes"))
        self.CritImm.setText(_translate("MainWindow", "Crit Imm"))
        self.PoisonImm.setText(_translate("MainWindow", "Poison Imm"))
        self.FireImm.setText(_translate("MainWindow", "Fire Imm"))
        self.StaggerImm.setText(_translate("MainWindow", "Stagger Imm"))
        self.SleepImm.setText(_translate("MainWindow", "Sleep Imm "))
        self.TumbleImm.setText(_translate("MainWindow", "Tumble Imm"))
        self.KBImm.setText(_translate("MainWindow", "KB Imm"))
        self.IceImm.setText(_translate("MainWindow", "Ice Imm"))
        self.label_3.setText(_translate("MainWindow", "<a href=\"https://github.com/Goldmoyai\">https://github.com/Goldmoyai</a>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/peppapon/patapon_editor.svg\"/></p></body></html>"))
import peppapon_rc
