# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1609, 984)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 60, 271, 861))
        self.groupBox.setObjectName("groupBox")
        self.PowerScaling_label = QtWidgets.QLabel(self.groupBox)
        self.PowerScaling_label.setGeometry(QtCore.QRect(10, 320, 91, 21))
        self.PowerScaling_label.setObjectName("PowerScaling_label")
        self.PowerScaling = QtWidgets.QLineEdit(self.groupBox)
        self.PowerScaling.setGeometry(QtCore.QRect(110, 320, 111, 20))
        self.PowerScaling.setText("")
        self.PowerScaling.setReadOnly(True)
        self.PowerScaling.setObjectName("PowerScaling")
        self.ShieldBreak = QtWidgets.QLineEdit(self.groupBox)
        self.ShieldBreak.setGeometry(QtCore.QRect(110, 350, 111, 20))
        self.ShieldBreak.setReadOnly(True)
        self.ShieldBreak.setObjectName("ShieldBreak")
        self.ShieldBreak_label = QtWidgets.QLabel(self.groupBox)
        self.ShieldBreak_label.setGeometry(QtCore.QRect(10, 350, 91, 21))
        self.ShieldBreak_label.setObjectName("ShieldBreak_label")
        self.ShieldBreakScaling_label = QtWidgets.QLabel(self.groupBox)
        self.ShieldBreakScaling_label.setGeometry(QtCore.QRect(10, 380, 101, 21))
        self.ShieldBreakScaling_label.setObjectName("ShieldBreakScaling_label")
        self.Power_label = QtWidgets.QLabel(self.groupBox)
        self.Power_label.setGeometry(QtCore.QRect(10, 290, 91, 20))
        self.Power_label.setObjectName("Power_label")
        self.ShieldBreakScaling = QtWidgets.QLineEdit(self.groupBox)
        self.ShieldBreakScaling.setGeometry(QtCore.QRect(110, 380, 111, 20))
        self.ShieldBreakScaling.setReadOnly(True)
        self.ShieldBreakScaling.setObjectName("ShieldBreakScaling")
        self.Power = QtWidgets.QLineEdit(self.groupBox)
        self.Power.setGeometry(QtCore.QRect(110, 290, 111, 20))
        self.Power.setReadOnly(True)
        self.Power.setObjectName("Power")
        self.Defense = QtWidgets.QLineEdit(self.groupBox)
        self.Defense.setGeometry(QtCore.QRect(110, 410, 111, 20))
        self.Defense.setReadOnly(True)
        self.Defense.setObjectName("Defense")
        self.DefenseScaling = QtWidgets.QLineEdit(self.groupBox)
        self.DefenseScaling.setGeometry(QtCore.QRect(110, 440, 111, 20))
        self.DefenseScaling.setReadOnly(True)
        self.DefenseScaling.setObjectName("DefenseScaling")
        self.Evasion = QtWidgets.QLineEdit(self.groupBox)
        self.Evasion.setGeometry(QtCore.QRect(110, 470, 111, 20))
        self.Evasion.setReadOnly(True)
        self.Evasion.setObjectName("Evasion")
        self.EvasionScaling = QtWidgets.QLineEdit(self.groupBox)
        self.EvasionScaling.setGeometry(QtCore.QRect(110, 500, 111, 20))
        self.EvasionScaling.setReadOnly(True)
        self.EvasionScaling.setObjectName("EvasionScaling")
        self.Weight = QtWidgets.QLineEdit(self.groupBox)
        self.Weight.setGeometry(QtCore.QRect(110, 530, 111, 20))
        self.Weight.setReadOnly(True)
        self.Weight.setObjectName("Weight")
        self.WeightScaling = QtWidgets.QLineEdit(self.groupBox)
        self.WeightScaling.setGeometry(QtCore.QRect(110, 560, 111, 20))
        self.WeightScaling.setReadOnly(True)
        self.WeightScaling.setObjectName("WeightScaling")
        self.Defense_label = QtWidgets.QLabel(self.groupBox)
        self.Defense_label.setGeometry(QtCore.QRect(10, 410, 101, 21))
        self.Defense_label.setObjectName("Defense_label")
        self.DefenseScaling_label = QtWidgets.QLabel(self.groupBox)
        self.DefenseScaling_label.setGeometry(QtCore.QRect(10, 440, 101, 21))
        self.DefenseScaling_label.setObjectName("DefenseScaling_label")
        self.Evasion_label = QtWidgets.QLabel(self.groupBox)
        self.Evasion_label.setGeometry(QtCore.QRect(10, 470, 101, 21))
        self.Evasion_label.setObjectName("Evasion_label")
        self.EvasionScaling_label = QtWidgets.QLabel(self.groupBox)
        self.EvasionScaling_label.setGeometry(QtCore.QRect(10, 500, 101, 21))
        self.EvasionScaling_label.setObjectName("EvasionScaling_label")
        self.Weight_label = QtWidgets.QLabel(self.groupBox)
        self.Weight_label.setGeometry(QtCore.QRect(10, 530, 101, 21))
        self.Weight_label.setObjectName("Weight_label")
        self.WeightScaling_label = QtWidgets.QLabel(self.groupBox)
        self.WeightScaling_label.setGeometry(QtCore.QRect(10, 560, 101, 21))
        self.WeightScaling_label.setObjectName("WeightScaling_label")
        self.MaxDMGScaling = QtWidgets.QLineEdit(self.groupBox)
        self.MaxDMGScaling.setGeometry(QtCore.QRect(110, 260, 110, 20))
        self.MaxDMGScaling.setReadOnly(True)
        self.MaxDMGScaling.setObjectName("MaxDMGScaling")
        self.MaxDMGScaling_label = QtWidgets.QLabel(self.groupBox)
        self.MaxDMGScaling_label.setGeometry(QtCore.QRect(10, 260, 101, 20))
        self.MaxDMGScaling_label.setObjectName("MaxDMGScaling_label")
        self.MinDMGScaling_label = QtWidgets.QLabel(self.groupBox)
        self.MinDMGScaling_label.setGeometry(QtCore.QRect(10, 200, 77, 13))
        self.MinDMGScaling_label.setObjectName("MinDMGScaling_label")
        self.MaxDMG_label = QtWidgets.QLabel(self.groupBox)
        self.MaxDMG_label.setGeometry(QtCore.QRect(10, 230, 61, 20))
        self.MaxDMG_label.setObjectName("MaxDMG_label")
        self.MaxDMG = QtWidgets.QLineEdit(self.groupBox)
        self.MaxDMG.setGeometry(QtCore.QRect(110, 230, 110, 20))
        self.MaxDMG.setReadOnly(True)
        self.MaxDMG.setObjectName("MaxDMG")
        self.MinDMG = QtWidgets.QLineEdit(self.groupBox)
        self.MinDMG.setGeometry(QtCore.QRect(109, 170, 110, 21))
        self.MinDMG.setReadOnly(True)
        self.MinDMG.setObjectName("MinDMG")
        self.MinDMGScaling = QtWidgets.QLineEdit(self.groupBox)
        self.MinDMGScaling.setGeometry(QtCore.QRect(109, 200, 110, 20))
        self.MinDMGScaling.setReadOnly(True)
        self.MinDMGScaling.setObjectName("MinDMGScaling")
        self.MinDMG_label = QtWidgets.QLabel(self.groupBox)
        self.MinDMG_label.setGeometry(QtCore.QRect(10, 170, 71, 21))
        self.MinDMG_label.setObjectName("MinDMG_label")
        self.AttackSpeed = QtWidgets.QLineEdit(self.groupBox)
        self.AttackSpeed.setGeometry(QtCore.QRect(110, 110, 110, 20))
        self.AttackSpeed.setObjectName("AttackSpeed")
        self.FeverSpeed = QtWidgets.QLineEdit(self.groupBox)
        self.FeverSpeed.setGeometry(QtCore.QRect(110, 80, 110, 20))
        self.FeverSpeed.setReadOnly(True)
        self.FeverSpeed.setObjectName("FeverSpeed")
        self.HPBase = QtWidgets.QLineEdit(self.groupBox)
        self.HPBase.setGeometry(QtCore.QRect(110, 20, 110, 20))
        self.HPBase.setReadOnly(True)
        self.HPBase.setObjectName("HPBase")
        self.HPScaling = QtWidgets.QLineEdit(self.groupBox)
        self.HPScaling.setGeometry(QtCore.QRect(110, 50, 110, 20))
        self.HPScaling.setReadOnly(True)
        self.HPScaling.setObjectName("HPScaling")
        self.HPBase_label = QtWidgets.QLabel(self.groupBox)
        self.HPBase_label.setGeometry(QtCore.QRect(11, 20, 111, 16))
        self.HPBase_label.setObjectName("HPBase_label")
        self.labelFeverSpeed_label = QtWidgets.QLabel(self.groupBox)
        self.labelFeverSpeed_label.setGeometry(QtCore.QRect(11, 80, 81, 16))
        self.labelFeverSpeed_label.setObjectName("labelFeverSpeed_label")
        self.HPScaling_label = QtWidgets.QLabel(self.groupBox)
        self.HPScaling_label.setGeometry(QtCore.QRect(11, 50, 111, 16))
        self.HPScaling_label.setObjectName("HPScaling_label")
        self.SprintSpeed_label = QtWidgets.QLabel(self.groupBox)
        self.SprintSpeed_label.setGeometry(QtCore.QRect(10, 140, 81, 16))
        self.SprintSpeed_label.setObjectName("SprintSpeed_label")
        self.SprintSpeed = QtWidgets.QLineEdit(self.groupBox)
        self.SprintSpeed.setGeometry(QtCore.QRect(110, 140, 110, 20))
        self.SprintSpeed.setReadOnly(True)
        self.SprintSpeed.setObjectName("SprintSpeed")
        self.AttackSpeed_label = QtWidgets.QLabel(self.groupBox)
        self.AttackSpeed_label.setGeometry(QtCore.QRect(11, 110, 70, 16))
        self.AttackSpeed_label.setObjectName("AttackSpeed_label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(980, 20, 159, 22))
        self.comboBox.setMaxVisibleItems(50)
        self.comboBox.setObjectName("comboBox")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 10, 21, 921))
        self.line.setMaximumSize(QtCore.QSize(21, 16777215))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.saveFileButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.saveFileButton_2.setGeometry(QtCore.QRect(200, 30, 121, 23))
        self.saveFileButton_2.setObjectName("saveFileButton_2")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(1250, 890, 120, 23))
        self.exitButton.setObjectName("exitButton")
        self.openFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.openFileButton.setGeometry(QtCore.QRect(80, 30, 120, 23))
        self.openFileButton.setObjectName("openFileButton")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(10, 930, 1571, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(1570, 0, 21, 951))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.fileName = QtWidgets.QLabel(self.centralwidget)
        self.fileName.setGeometry(QtCore.QRect(330, 30, 261, 16))
        self.fileName.setText("")
        self.fileName.setObjectName("fileName")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, -10, 1141, 41))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.loadedCount = QtWidgets.QLCDNumber(self.centralwidget)
        self.loadedCount.setEnabled(True)
        self.loadedCount.setGeometry(QtCore.QRect(890, 20, 64, 23))
        self.loadedCount.setAutoFillBackground(False)
        self.loadedCount.setObjectName("loadedCount")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(280, 60, 731, 871))
        self.groupBox_2.setObjectName("groupBox_2")
        self.CritBase = QtWidgets.QLineEdit(self.groupBox_2)
        self.CritBase.setGeometry(QtCore.QRect(110, 30, 110, 20))
        self.CritBase.setReadOnly(True)
        self.CritBase.setObjectName("CritBase")
        self.CritBase_label = QtWidgets.QLabel(self.groupBox_2)
        self.CritBase_label.setGeometry(QtCore.QRect(10, 30, 111, 16))
        self.CritBase_label.setObjectName("CritBase_label")
        self.CritScaling = QtWidgets.QLineEdit(self.groupBox_2)
        self.CritScaling.setGeometry(QtCore.QRect(110, 61, 110, 20))
        self.CritScaling.setReadOnly(True)
        self.CritScaling.setObjectName("CritScaling")
        self.CritScaling_label = QtWidgets.QLabel(self.groupBox_2)
        self.CritScaling_label.setGeometry(QtCore.QRect(10, 60, 111, 16))
        self.CritScaling_label.setObjectName("CritScaling_label")
        self.KBBase = QtWidgets.QLineEdit(self.groupBox_2)
        self.KBBase.setGeometry(QtCore.QRect(110, 91, 110, 20))
        self.KBBase.setObjectName("KBBase")
        self.KBBase_label = QtWidgets.QLabel(self.groupBox_2)
        self.KBBase_label.setGeometry(QtCore.QRect(10, 90, 47, 20))
        self.KBBase_label.setObjectName("KBBase_label")
        self.KBScaling = QtWidgets.QLineEdit(self.groupBox_2)
        self.KBScaling.setGeometry(QtCore.QRect(110, 120, 110, 20))
        self.KBScaling.setObjectName("KBScaling")
        self.KBScaling_label = QtWidgets.QLabel(self.groupBox_2)
        self.KBScaling_label.setGeometry(QtCore.QRect(10, 120, 47, 13))
        self.KBScaling_label.setObjectName("KBScaling_label")
        self.KBScaling_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.KBScaling_2.setGeometry(QtCore.QRect(110, 150, 110, 20))
        self.KBScaling_2.setObjectName("KBScaling_2")
        self.KBScaling_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.KBScaling_3.setGeometry(QtCore.QRect(110, 180, 110, 20))
        self.KBScaling_3.setObjectName("KBScaling_3")
        self.KBScaling_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.KBScaling_4.setGeometry(QtCore.QRect(110, 210, 110, 20))
        self.KBScaling_4.setText("")
        self.KBScaling_4.setObjectName("KBScaling_4")
        self.KBScaling_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.KBScaling_5.setGeometry(QtCore.QRect(110, 240, 110, 20))
        self.KBScaling_5.setObjectName("KBScaling_5")
        self.KBScaling_6 = QtWidgets.QLineEdit(self.groupBox_2)
        self.KBScaling_6.setGeometry(QtCore.QRect(110, 270, 110, 20))
        self.KBScaling_6.setObjectName("KBScaling_6")
        self.KBScaling_7 = QtWidgets.QLineEdit(self.groupBox_2)
        self.KBScaling_7.setGeometry(QtCore.QRect(110, 300, 110, 20))
        self.KBScaling_7.setObjectName("KBScaling_7")
        self.KBScaling_8 = QtWidgets.QLineEdit(self.groupBox_2)
        self.KBScaling_8.setGeometry(QtCore.QRect(110, 330, 110, 20))
        self.KBScaling_8.setObjectName("KBScaling_8")
        self.KBScaling_9 = QtWidgets.QLineEdit(self.groupBox_2)
        self.KBScaling_9.setGeometry(QtCore.QRect(110, 360, 110, 20))
        self.KBScaling_9.setObjectName("KBScaling_9")
        self.KBScaling_10 = QtWidgets.QLineEdit(self.groupBox_2)
        self.KBScaling_10.setGeometry(QtCore.QRect(110, 390, 110, 20))
        self.KBScaling_10.setObjectName("KBScaling_10")
        self.KBScaling_11 = QtWidgets.QLineEdit(self.groupBox_2)
        self.KBScaling_11.setGeometry(QtCore.QRect(110, 420, 110, 20))
        self.KBScaling_11.setObjectName("KBScaling_11")
        self.KBScaling_12 = QtWidgets.QLineEdit(self.groupBox_2)
        self.KBScaling_12.setGeometry(QtCore.QRect(110, 450, 110, 20))
        self.KBScaling_12.setObjectName("KBScaling_12")
        self.Crush = QtWidgets.QCheckBox(self.groupBox_2)
        self.Crush.setGeometry(QtCore.QRect(340, 40, 70, 17))
        self.Crush.setCheckable(False)
        self.Crush.setObjectName("Crush")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1609, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Potapon Resource File Editor"))
        self.groupBox.setTitle(_translate("MainWindow", "BaseStats"))
        self.PowerScaling_label.setText(_translate("MainWindow", "Power Scaling"))
        self.ShieldBreak_label.setText(_translate("MainWindow", "Shield Break"))
        self.ShieldBreakScaling_label.setText(_translate("MainWindow", "Shield Break Scaling"))
        self.Power_label.setText(_translate("MainWindow", "Power"))
        self.Defense_label.setText(_translate("MainWindow", "Defense"))
        self.DefenseScaling_label.setText(_translate("MainWindow", "Defense Scaling"))
        self.Evasion_label.setText(_translate("MainWindow", "Evasion"))
        self.EvasionScaling_label.setText(_translate("MainWindow", "Evasion Scaling"))
        self.Weight_label.setText(_translate("MainWindow", "Weight"))
        self.WeightScaling_label.setText(_translate("MainWindow", "Weight Scaling"))
        self.MaxDMGScaling_label.setText(_translate("MainWindow", "Max DMG Scaling"))
        self.MinDMGScaling_label.setText(_translate("MainWindow", "Min DMG Scaling"))
        self.MaxDMG_label.setText(_translate("MainWindow", "MaxDMG"))
        self.MinDMG_label.setText(_translate("MainWindow", "Min DMG"))
        self.HPBase_label.setText(_translate("MainWindow", "HP Base"))
        self.labelFeverSpeed_label.setText(_translate("MainWindow", "Fever Speed"))
        self.HPScaling_label.setText(_translate("MainWindow", "HP Scaling"))
        self.SprintSpeed_label.setText(_translate("MainWindow", "Sprint Speed"))
        self.AttackSpeed_label.setText(_translate("MainWindow", "Attack Speed"))
        self.saveFileButton_2.setText(_translate("MainWindow", "Сохранить файл"))
        self.exitButton.setText(_translate("MainWindow", "Выход"))
        self.openFileButton.setText(_translate("MainWindow", " Открыть файл"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Status Effects"))
        self.CritBase_label.setText(_translate("MainWindow", "Crit Base"))
        self.CritScaling_label.setText(_translate("MainWindow", "Crit Scaling"))
        self.KBBase_label.setText(_translate("MainWindow", "KB Base"))
        self.KBScaling_label.setText(_translate("MainWindow", "KB Scaling"))
        self.Crush.setText(_translate("MainWindow", "Crush"))
